# Generated by Django 5.2.6 on 2025-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='Name of the email template used', max_length=100, verbose_name='template name')),
                ('recipient_email', models.EmailField(help_text='Email address of the recipient', max_length=254, verbose_name='recipient email')),
                ('subject', models.CharField(help_text='Rendered email subject', max_length=255, verbose_name='subject')),
                ('body_html', models.TextField(blank=True, help_text='Rendered HTML email body', verbose_name='HTML body')),
                ('body_text', models.TextField(blank=True, help_text='Rendered plain text email body', verbose_name='text body')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', help_text='Delivery status of the email', max_length=20, verbose_name='status')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed', verbose_name='error message')),
                ('sent_at', models.DateTimeField(blank=True, help_text='Timestamp when email was sent', null=True, verbose_name='sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Template variables used for rendering', verbose_name='variables')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of delivery attempts', verbose_name='retry count')),
                ('max_retries', models.PositiveIntegerField(default=3, help_text='Maximum number of retry attempts', verbose_name='max retries')),
                ('next_retry_at', models.DateTimeField(blank=True, help_text='Next retry attempt timestamp', null=True, verbose_name='next retry at')),
            ],
            options={
                'verbose_name': 'Email Notification',
                'verbose_name_plural': 'Email Notifications',
                'db_table': 'email_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique identifier for the template', max_length=100, unique=True, verbose_name='name')),
                ('subject', models.CharField(help_text='Email subject line (supports variables)', max_length=255, verbose_name='subject')),
                ('body_html', models.TextField(help_text='HTML version of the email (supports variables)', verbose_name='HTML body')),
                ('body_text', models.TextField(help_text='Plain text version of the email (supports variables)', verbose_name='text body')),
                ('variables', models.JSONField(blank=True, default=dict, help_text='Available template variables and their descriptions', verbose_name='variables')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', help_text='Template language', max_length=2, verbose_name='language')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('transaction_created', 'Transaction Created'), ('transaction_updated', 'Transaction Updated'), ('status_changed', 'Status Changed'), ('assignment_changed', 'Assignment Changed'), ('comment_added', 'Comment Added'), ('file_uploaded', 'File Uploaded'), ('due_date_reminder', 'Due Date Reminder'), ('overdue_alert', 'Overdue Alert'), ('welcome', 'Welcome Email'), ('password_reset', 'Password Reset')], help_text='Type of notification', max_length=50, verbose_name='notification type')),
                ('email_enabled', models.BooleanField(default=True, help_text='Whether to send email notifications', verbose_name='email enabled')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Whether to show in-app notifications', verbose_name='in-app enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
    ]
