# Generated by Django 5.2.6 on 2025-09-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotification',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Related transaction (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_notifications', to='transactions.transaction', verbose_name='transaction'),
        ),
    ]
