# Generated by Django 5.2.6 on 2025-09-17 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_initial'),
        ('transactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200, verbose_name='title')),
                ('message', models.TextField(help_text='Notification message content', verbose_name='message')),
                ('type', models.CharField(choices=[('transaction', 'Transaction'), ('system', 'System'), ('user', 'User'), ('report', 'Report')], default='system', help_text='Type of notification', max_length=20, verbose_name='type')),
                ('category', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', help_text='Category/severity of notification', max_length=20, verbose_name='category')),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read', verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was read', null=True, verbose_name='read at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('action_link', models.CharField(blank=True, help_text='Optional link for notification action', max_length=255, verbose_name='action link')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data', verbose_name='metadata')),
                ('transaction', models.ForeignKey(blank=True, help_text='Related transaction (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='transactions.transaction', verbose_name='transaction')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'), models.Index(fields=['type'], name='notificatio_type_8a8a78_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
