# Generated by Django 5.2.6 on 2025-09-13 08:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0002_initial'),
        ('transactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('stage_type', models.CharField(choices=[('start', 'Start'), ('task', 'Task'), ('review', 'Review'), ('approval', 'Approval'), ('conditional', 'Conditional'), ('parallel', 'Parallel'), ('end', 'End')], max_length=50)),
                ('assigned_role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('editor', 'Editor'), ('client', 'Client'), ('auto', 'Auto Assign')], max_length=50)),
                ('duration_days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_optional', models.BooleanField(default=False)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('requires_comment', models.BooleanField(default=False)),
                ('auto_complete', models.BooleanField(default=False)),
                ('auto_complete_conditions', models.JSONField(blank=True, default=dict)),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='workflow_stages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['workflow', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_workflows', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_workflows', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to='transactions.transaction')),
                ('current_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_instances', to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escalation_after_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('escalate_to_role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('supervisor', 'Supervisor')], max_length=50)),
                ('notification_template', models.TextField(blank=True)),
                ('max_escalations', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('escalate_to_users', models.ManyToManyField(blank=True, related_name='escalations', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='workflows.workflowstage')),
            ],
            options={
                'ordering': ['stage', 'escalation_after_hours'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField()),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('exit_comment', models.TextField(blank=True)),
                ('attachments', models.ManyToManyField(blank=True, to='attachments.attachment')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_entries', to=settings.AUTH_USER_MODEL)),
                ('exited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_exits', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowstage')),
                ('workflow_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='workflows.workflowinstance')),
            ],
            options={
                'ordering': ['workflow_instance', 'entered_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('translation', 'Translation'), ('documentation', 'Documentation'), ('review', 'Review'), ('approval', 'Approval'), ('custom', 'Custom')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_parallel_stages', models.BooleanField(default=False)),
                ('auto_assign', models.BooleanField(default=False)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workflowstage',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='workflows.workflowtemplate'),
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('assignment', 'Auto Assignment'), ('escalation', 'Escalation'), ('notification', 'Notification'), ('validation', 'Validation'), ('calculation', 'Calculation')], max_length=50)),
                ('trigger_event', models.CharField(choices=[('stage_enter', 'Stage Enter'), ('stage_exit', 'Stage Exit'), ('time_elapsed', 'Time Elapsed'), ('condition_met', 'Condition Met')], max_length=50)),
                ('condition', models.JSONField(default=dict)),
                ('action', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('trigger_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workflows.workflowstage')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workflows.workflowtemplate')),
            ],
            options={
                'ordering': ['workflow', 'priority'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflows.workflowtemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstage',
            unique_together={('workflow', 'order')},
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('always', 'Always'), ('approval', 'On Approval'), ('rejection', 'On Rejection'), ('condition', 'Conditional'), ('manual', 'Manual')], default='always', max_length=50)),
                ('condition_data', models.JSONField(blank=True, default=dict)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('from_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflows.workflowstage')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflows.workflowstage')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflows.workflowtemplate')),
            ],
            options={
                'ordering': ['workflow', 'from_stage', 'priority'],
                'unique_together': {('workflow', 'from_stage', 'to_stage')},
            },
        ),
    ]
