# Generated by Django 5.2.6 on 2025-09-12 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_configurations', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who triggered this log entry (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='systemmaintenancemode',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access the system during maintenance', related_name='maintenance_access', to=settings.AUTH_USER_MODEL, verbose_name='allowed users'),
        ),
        migrations.AddField(
            model_name='systemmaintenancemode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_modes', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='systemmaintenancemode',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_maintenance_modes', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddIndex(
            model_name='systemconfiguration',
            index=models.Index(fields=['environment', 'is_active'], name='system_conf_environ_cb8d15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='systemconfiguration',
            unique_together={('name', 'environment')},
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['level', 'created_at'], name='system_logs_level_5a2647_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['category', 'created_at'], name='system_logs_categor_203279_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['user', 'created_at'], name='system_logs_user_id_9ba726_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['-created_at'], name='system_logs_created_9fcafe_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['key'], name='system_sett_key_052b30_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['category'], name='system_sett_categor_db5b74_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsetting',
            index=models.Index(fields=['is_editable'], name='system_sett_is_edit_5465da_idx'),
        ),
    ]
