# Generated by Django 5.2.6 on 2025-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content', verbose_name='content')),
                ('is_internal', models.BooleanField(default=True, help_text='Internal comments are not visible to clients', verbose_name='is internal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Auto-generated unique transaction identifier', max_length=20, unique=True, verbose_name='transaction ID')),
                ('reference_number', models.CharField(help_text='External client reference number', max_length=50, verbose_name='reference number')),
                ('client_name', models.CharField(help_text='Name of the client or organization', max_length=255, verbose_name='client name')),
                ('transaction_type', models.CharField(help_text='Type of work or process', max_length=50, verbose_name='transaction type')),
                ('category', models.CharField(blank=True, choices=[('architecture', 'Architecture'), ('engineering', 'Engineering'), ('construction', 'Construction'), ('planning', 'Planning'), ('consultation', 'Consultation')], help_text='Work category classification', max_length=50, verbose_name='category')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the transaction', max_length=2000, verbose_name='description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='draft', help_text='Current transaction status', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Transaction priority level', max_length=10, verbose_name='priority')),
                ('due_date', models.DateField(blank=True, help_text='Expected completion date', null=True, verbose_name='due date')),
                ('department', models.CharField(blank=True, help_text='Responsible department', max_length=100, verbose_name='department')),
                ('project_id', models.CharField(blank=True, help_text='Related project identifier', max_length=50, verbose_name='project ID')),
                ('qr_code', models.TextField(blank=True, help_text='Base64 encoded QR code for quick access', verbose_name='QR code')),
                ('tags', models.TextField(blank=True, help_text='Searchable keywords (comma-separated)', verbose_name='tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag', verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, help_text='Status before the change', max_length=20, verbose_name='previous status')),
                ('new_status', models.CharField(help_text='Status after the change', max_length=20, verbose_name='new status')),
                ('change_reason', models.TextField(blank=True, help_text='Optional reason for the status change', verbose_name='change reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Transaction Status History',
                'verbose_name_plural': 'Transaction Status Histories',
                'db_table': 'transaction_status_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
