# Generated by Django 5.2.6 on 2025-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_category_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='', help_text='Transaction title or brief description', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='External client reference number', max_length=50, verbose_name='reference number'),
        ),
    ]
