# Generated by Django 5.2.6 on 2025-09-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_title_alter_transaction_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes not visible to clients', verbose_name='internal notes'),
        ),
    ]
