# Generated by Django 5.2.6 on 2025-09-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_internal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for optimistic locking', verbose_name='version'),
        ),
    ]
