# Generated by Django 5.2.6 on 2025-09-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(help_text='Original name of the uploaded file', max_length=255, verbose_name='original filename')),
                ('stored_filename', models.CharField(help_text='Name used for storing the file on disk', max_length=255, verbose_name='stored filename')),
                ('file_path', models.CharField(help_text='Full path to the stored file', max_length=500, verbose_name='file path')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes', verbose_name='file size')),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100, verbose_name='MIME type')),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash for duplicate detection', max_length=64, verbose_name='file hash')),
                ('is_client_visible', models.BooleanField(default=True, help_text='Whether clients can see and download this file', verbose_name='is client visible')),
                ('description', models.TextField(blank=True, help_text='Optional description of the file', verbose_name='description')),
                ('virus_scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Error')], default='pending', help_text='Status of virus scanning', max_length=20, verbose_name='virus scan status')),
                ('virus_scan_result', models.TextField(blank=True, help_text='Details from virus scan', verbose_name='virus scan result')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
