# Generated by Django 5.2.6 on 2025-09-12 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_attachments', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='transaction',
            field=models.ForeignKey(help_text='Transaction this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='transactions.transaction', verbose_name='transaction'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded this file', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['transaction'], name='attachments_transac_05eb06_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['uploaded_by'], name='attachments_uploade_77499a_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['file_hash'], name='attachments_file_ha_ad54cc_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['is_client_visible'], name='attachments_is_clie_151ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['virus_scan_status'], name='attachments_virus_s_958e38_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['created_at'], name='attachments_created_d487af_idx'),
        ),
    ]
