# Generated by Django 5.2.6 on 2025-09-12 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Unique token for email verification', max_length=64, unique=True, verbose_name='token')),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp', verbose_name='expires at')),
                ('used', models.BooleanField(default=False, help_text='Whether token has been used', verbose_name='used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when token was used', null=True, verbose_name='used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'email_verification_tokens',
                'indexes': [models.Index(fields=['token'], name='email_verif_token_df7c5e_idx'), models.Index(fields=['user'], name='email_verif_user_id_bef55e_idx'), models.Index(fields=['expires_at'], name='email_verif_expires_770728_idx')],
            },
        ),
    ]
