# Generated by Django 5.2.6 on 2025-09-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='URL to user profile picture from Google or other sources', max_length=500, null=True, verbose_name='profile picture URL'),
        ),
    ]
