# Generated by Django 5.2.6 on 2025-09-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_comment',
            field=models.BooleanField(default=False, help_text='Whether client user can add comments to transactions', verbose_name='can comment'),
        ),
    ]
