# Generated by Django 5.2.6 on 2025-09-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('status_change', 'Status Change'), ('file_upload', 'File Upload'), ('file_download', 'File Download'), ('file_delete', 'File Delete'), ('export', 'Export'), ('import', 'Import'), ('permission_denied', 'Permission Denied'), ('view', 'View'), ('search', 'Search'), ('other', 'Other')], help_text='Type of action performed', max_length=50, verbose_name='action')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object ID')),
                ('table_name', models.CharField(help_text='Database table name', max_length=50, verbose_name='table name')),
                ('record_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the affected record', null=True, verbose_name='record ID')),
                ('old_values', models.JSONField(blank=True, help_text='Values before the change (JSON format)', null=True, verbose_name='old values')),
                ('new_values', models.JSONField(blank=True, help_text='Values after the change (JSON format)', null=True, verbose_name='new values')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action', verbose_name='description')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the action was performed', null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', verbose_name='user agent')),
                ('session_id', models.CharField(blank=True, help_text='Session identifier', max_length=255, verbose_name='session ID')),
                ('request_method', models.CharField(blank=True, help_text='HTTP request method (GET, POST, etc.)', max_length=10, verbose_name='request method')),
                ('request_path', models.CharField(blank=True, help_text='Request URL path', max_length=500, verbose_name='request path')),
                ('response_status', models.PositiveIntegerField(blank=True, help_text='HTTP response status code', null=True, verbose_name='response status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
