# Generated by Django 5.2.6 on 2025-09-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session identifier', max_length=255, null=True, verbose_name='session ID'),
        ),
    ]
